#ifndef WARP_ENTITYATTRIBUTEMACROS_H
#define WARP_ENTITYATTRIBUTEMACROS_H

// Stable

/// Factory
#define FACTORY_BASE_COST 100
#define FACTORY_BASE_MAX_HP 1000
#define FACTORY_BASE_ATTACK 100

/// LaserTower
#define LASERTOWER_BASE_COST 100
#define LASERTOWER_BASE_MAX_HP 1000
#define LASERTOWER_BASE_ATTACK 100

/// TeslaCoil
#define TESLACOIL_BASE_COST 100
#define TESLACOIL_BASE_MAX_HP 1000
#define TESLACOIL_BASE_ATTACK 100

/// SniperTower
#define SNIPERTOWER_BASE_COST 100
#define SNIPERTOWER_BASE_MAX_HP 1000
#define SNIPERTOWER_BASE_ATTACK 100

/// HqAttack
#define HQATTACK_BASE_COST 100
#define HQATTACK_BASE_MAX_HP 1000
#define HQATTACK_BASE_ATTACK 100

/// HqDefense
#define HQDEFENSE_BASE_COST 100
#define HQDEFENSE_BASE_MAX_HP 1000
#define HQDEFENSE_BASE_ATTACK 100

/// Special
#define SPECIAL_BASE_COST 100
#define SPECIAL_BASE_MAX_HP 1000
#define SPECIAL_BASE_ATTACK 100

// Unstable



#endif //WARP_ENTITYATTRIBUTEMACROS_H
